copy C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00000.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00001.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00002.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00003.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00004.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00005.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00006.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00007.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00008.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00009.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00010.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00011.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00012.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00013.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00014.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00015.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00016.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00017.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00018.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00019.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00020.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00021.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00022.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00023.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00024.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00025.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00026.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00027.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00028.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00029.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00030.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00031.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00032.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00033.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00034.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00035.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00036.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00037.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00038.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00039.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00040.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00041.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00042.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00043.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00044.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00045.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00046.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00047.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00048.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00049.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00050.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00051.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00052.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00053.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00054.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00055.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00056.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00057.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00058.avs out.yuv
copy /b out.yuv + C:\Users\ioannis.k\Documents\Personal\Netflix\chunked_encoder_setup_files\sources\Heroes_10secChunk_80mbps_00059.avs out.yuv
